name: Check

on:
  push:
    branches: ["trunk"]
  pull_request:
    branches: ["**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  conformance:
    name: Conformance

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        name: Checkout

      - uses: crate-ci/typos@v1
        name: Spellcheck

      - uses: actions/setup-go@v5
        name: Configure Go

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.8

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.24.x", "1.25.x"]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Run test
        run: make test COVERAGE_DIR=/tmp/coverage

  release:
    name: Release
    needs: [lint, test]
    runs-on: ubuntu-latest

    if: ${{ success() && github.repository == 'aslilac/calliope-migrate' && startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: softprops/action-gh-release@v1
        name: Release
